- build/app/public/css/popup.css
- shared/scss/views/_page-connection.scss
https://app.asana.com/0/0/1203101336846003/f
Before: 
After:
> right-align text on the certificates screen

- build/app/public/js/base.js
- integration-tests/browser.spec-int.js
- schema/__generated__/schema.parsers.js
- schema/__generated__/schema.types.ts
- schema/get-privacy-dashboard-data.json
**Reviewer:**
https://app.asana.com/0/892838074342800/1203466326045183/f
We were being overly strict on incoming email data - validating fields that we didn't actually use, this PR ensures that those fields are truly optional
> fix(extension): only require a single field for email data

- build/app/public/js/base.js
- shared/js/ui/templates/shared/links.js
**Reviewer:**
Prevents a long-press popover on the "Disable in Settings" button in iOS
> Prevent a draggable link popover on iOS

- build/app/public/css/popup.css
- shared/scss/views/_tracker-networks.scss
**Reviewer:**
https://app.asana.com/0/1200835453786799/1204540803335733/f
> fixed render of tracker icon

- .github/dependabot.yml
> adding dependabot

- .github/workflows/tests.yml
> run clean-tree at the correct time

- build/app/public/css/popup.css
- shared/scss/popup.scss
**Reviewer:**
https://app.asana.com/0/1200835453786799/1206926447697272/f
1. run in macOS
2. visit a site with a lot of trackers
3. click the 'requests blocked from loading' menu item in the dashboard.
4. verify the list can be scrolled when taller than the application window
> fix: window not scrolling with long lists

- shared/js/ui/views/tests/generate-data.mjs
Adding an example of:
- 1 tracker with a rule exception
- 1 third party request (none-tracker)
> added another example data set

- .github/workflows/tests.yml
- integration-tests/browser.spec-int.js
https://app.asana.com/0/1200835453786799/1207868371624521/f
POC for running in macOS
Future PRs will enable more
> ci tweaks - run on macos-latest

- build/app/public/js/base.js
- integration-tests/DashboardPage.js
- integration-tests/ios.spec-int.js
- shared/js/ui/platform-features.mjs
- v2/breakage-categories.js
- v2/screens/breakage-form-screen.jsx
- v2/screens/choice-problem.jsx
https://app.asana.com/0/1201141132935289/1207850148122030/f
- Introduced a new flag for randomized categories - defaults to 'true'
- a URL param can set it to false (to help tests)
- I moved logic out of the components into a feature factory 
See the Asana task
- npm run preview
- Verify the Category Selection list is random
- http://localhost:3000/html/ios.html?screen=categorySelection
- Verify the regular form screen is displaying categories in a random order too
-  http://localhost:3000/html/ios.html?screen=breakageForm
| Screen: categorySelection | Screen: breakageForm |
|---------|---------|
| <img width="413" alt="image" src="https://github.com/user-attachments/assets/1c56ad38-e743-44a4-a161-5c72bd67c126"> | <img width="414" alt="image" …
> shuffle categories

- build/app/public/js/base.js
- integration-tests/DashboardPage.js
- integration-tests/Extension.js
- integration-tests/Mocks.js
- integration-tests/browser.spec-int.js
- integration-tests/helpers.js
- integration-tests/utils/common-flows.js
- schema/__generated__/schema.parsers.mjs
- schema/__generated__/schema.types.ts
- schema/api.json
- schema/extension-incoming.json
- schema/extension-outgoing.json
- schema/schema.test.mjs
- shared/js/browser/browser-communication.js
- shared/js/browser/utils/communication-mocks.mjs
- shared/js/ui/components/toggle-report.jsx
- shared/js/ui/components/toggle-report/toggle-report-provider.jsx
- shared/js/ui/views/tests/generate-data.mjs
- types.ts
- v2/data-provider.js
- v2/screens/toggle-report-screen.jsx
- https://app.asana.com/0/0/1208167615504464/f
Tested extensively with @kzar  - we're making a semver major release and he'll handle the extension update to suite.
> use extension connection

- build/app/public/js/base.js
- v2/components/custom-element-loader.jsx
https://app.asana.com/0/1200835453786799/1208424430637685/f
We used `??=`, which is breaking Android's integration tests due to a very old WebView being used.
> fix: remove new syntax

- package-lock.json
- package.json
https://app.asana.com/0/1200835453786799/1208517062230157/f
Just a TS upgrade
> deps: upgrade typescript

- guides/toggle-report.md
Adds missing example JSON payload to [Toggle Report guide](https://duckduckgo.github.io/privacy-dashboard/documents/Guides.Toggle_Report.html)
> Adds JSON example to Toggle Report guide

- shared/js/browser/utils/communication-mocks.mjs
- shared/js/browser/windows-communication.js
https://app.asana.com/0/1201462763372786/1208639026189901/f
**Reviewer:**
> windows interop messaging

- package.json
Asana: https://app.asana.com/0/892838074342800/1208818404558767/f
Fixes missing schema folder in npm package
1. Check out locally
2. Run `npm pack`
3. Check that contents of package file include paths `schema/__generated__` and `schema/__fixtures__`
> Adds schema folder to NPM package

- .github/workflows/tests.yml
Updates `actions/upload-artifact` to v4 as per https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
1. Check that the Test & Deploy action (tests.yml) runs successfully. [Failure example](https://github.com/duckduckgo/privacy-dashboard/actions/runs/13133661316)
2. Check that the Action summary one downloadable artifact (playwright-report.zip)
> Updated to actions/upload-artifact@v4

- .github/workflows/tests.yml
Updates action dependencies for tests.yml
> Workflow actions update

- .github/workflows/update-snapshots.yml
- package-lock.json
- package.json
> update ts deps

- integration-tests/android.spec-int.js
- integration-tests/windows.spec-int.js
- schema/__generated__/schema.parsers.mjs
- schema/__generated__/schema.types.ts
- schema/api.json
- schema/cert-data.json
- shared/js/browser/macos-communication.js
- shared/js/browser/utils/communication-mocks.mjs
- shared/js/ui/platform-features.mjs
- shared/js/ui/templates/page-non-trackers.js
- shared/js/ui/views/tests/generate-data.mjs
https://app.asana.com/0/1200835453786799/1209596405812840
macOS / iOS will be adding 'isInvalidCert', so we now wait for this before we render. This prevents a flash of the wrong screen.
> Fixing implicit invalid certs

- shared/js/ui/templates/key-insights.js
- shared/locales/bg/site.json
- shared/locales/cs/site.json
- shared/locales/da/site.json
- shared/locales/de/site.json
- shared/locales/el/site.json
- shared/locales/en/site.json
- shared/locales/es/site.json
- shared/locales/et/site.json
- shared/locales/fi/site.json
- shared/locales/fr/site.json
- shared/locales/hr/site.json
- shared/locales/hu/site.json
- shared/locales/it/site.json
- shared/locales/lt/site.json
- shared/locales/lv/site.json
- shared/locales/nb/site.json
- shared/locales/nl/site.json
- shared/locales/pl/site.json
- shared/locales/pt/site.json
- shared/locales/ro/site.json
- shared/locales/ru/site.json
- shared/locales/sk/site.json
- shared/locales/sl/site.json
- shared/locales/sv/site.json
- shared/locales/tr/site.json
Asana: https://app.asana.com/1/137249556945/project/72649045549333/task/1210075972793595?focus=true
- Updates translations for Scam Blocker help link
- Unifies duplicate translations into one key
1. Visit preview samples and confirm that translations match JSON
- [Phishing](https://deploy-preview-1733--content-scope-scripts.netlify.app/build/pages/special-error/?errorId=phishing&platform=ios&locale=it)
- [Malware](https://deploy-preview-1733--content-scope-scripts.netlify.app/build/pages/special-error/?errorId=malware&platform=ios&locale=it)
- [Scam](https://deploy-preview-1733--content-scope-scripts.netlify.app/build/pages/special-error/?errorId=scam&platform=ios&locale=it)
> Scam Blocker translations
