build/app/public/js/base.js, shared/js/ui/views/search.es6.js
**Reviewer:**
we were calling `window.close()` following a form submission which was causing some messages
to not be delivered to the service worker.
1. Open the dashboard in the extension on MV3
2. Perform a search
3. It should always work (it was flaky before)
=> fix(extension): fix search on MV3

build/app/public/js/base.js, shared/js/browser/utils/__snapshots__/request-details.test.js.snap, shared/js/browser/utils/request-details.js, shared/js/browser/utils/request-details.test.js
https://app.asana.com/0/1200835453786799/1203483081595499/f
In this case, 'entityName' and 'eTLDplus1' match - our logic
was always running `removeTLD` when the entity name was present.
This behaviour was intended to prevent Entity names like "Amazon.com" from displaying,
but it accidentally also stripped `.uk` from the example below.
The added test ensures that the following is true for the given request:
`"displayName": "bbci.co.uk"`
=> fix: display name when entityName matches eTLD+1

build/app/public/js/base.js, integration-tests/DashboardPage.js, integration-tests/Mocks.js, integration-tests/browser.spec-int.js, integration-tests/helpers.js, shared/js/ui/base/localize.es6.js
https://app.asana.com/0/1200835453786799/1203485757983743/f
in our extensions, we were not using `chrome.i18n.getUILanguage()` to determine the correct browser UI language.
=> fix(extensions): use chrome.i18n for language selection

Package.swift, swift-package/Sources/Bundle.swift
**Asana task:** https://app.asana.com/0/1200835453786799/1203532353505600/f
Change how we bundle assets for Apple platforms. We want to exclude woff/woff2 font files from the bundle. To do so we add their path to exclude list but at the same time we need to specify subfolders and files that we want to include explicitly.
Additional we need to update the resource bundle path to html file as we no longer include the topmost 'app' folder. 
1. Setup iOS and macOS clients using local BSK copy.
2. In BSK's Package.swift update the PD reference to: `.package(url: "https://github.com/duckduckgo/privacy-dashboard", .revision("fe3eb73718e20ba2c2e61d726fa93edddafbaacf"))`
3. Do a clean build of iOS and macOS to test if PD opens and works properly.
=> Exclude font assets from Swift Package bundle

build/app/public/js/base.js, shared/js/browser/utils/__snapshots__/request-details.test.js.snap, shared/js/browser/utils/request-details.js, shared/js/browser/utils/request-details.test.js
Removes the port from the site's `domain`. This fixes a downstream issue in the extension where we expect allowlisted domains to be hostname only (i.e. without port).
=> Hide port from domain in the dashboard.

build/app/public/js/base.js, shared/js/ui/templates/breakage-form.es6.js
**Reviewer:**
The list of categories for the breakage form was being generated at script load time, at which point locales were not loaded yet. This meant that the category labels were always in English.
This PR moves this loading to render-time, which means that it should properly render in the current language.
=> Fix breakage form localization

build/app/public/css/popup.css, shared/scss/views/_cta-screens.scss
**Reviewer:**
The "Share DuckDuckGo" CTA button text was wrapping in some languages. This PR increases the max-width of this element so this always fits on one line:
Before:
After:
1. `npm run preview`
2. Visit http://127.0.0.1:3210/html/popup.html?platform=browser&theme=light&specialDomainName=extensions&state=04&locale=lt
3. Check that the text doesn't wrap.
=> Increase max-width of "Share DuckDuckGo" CTA button to fit all languages

build/app/public/js/base.js, scripts/bundle.mjs
**Reviewer:**
- Just a safe-guard to match the build target we use in AutoConsent & C-S-S.
- I don't think this is technically needed, but before we push a large update to Android I'd rather be consistent with out JS bundles we produce :)
=> esbuild: 2021 target to match C-S-S

.github/workflows/tests.yml
This pull request changes the directory in the `copy-to-docs` command in the tests workflow.
In our GitHub Actions' tests workflow, we've changed the `copy-to-docs` step. Specifically, it now copies from `build/app-debug/` instead of `build/app/`.
Once the PR is merged, the dashboard should be accessible  at https://duckduckgo.github.io/privacy-dashboard/app-debug <- this is important to be the debug build because it uses mocked communications.
Required to view the dashboard via the docs
=> fixed debug deployment

debugger/debugger.jsx, package.json, shared/js/ui/views/tests/generate-data.mjs, tsconfig.json, types.ts
https://app.asana.com/0/0/1207195637811329/f
Update debugger to reflect url parameters and fix initial state loading. This will be needed in the next PR to preview/debug another new screen.
- Updated debugger to reflect url parameters
- Fixed initial state loading
- Verify URL parameters are reflected correctly
- `npm run preview`
- then select one of the new options in the select menu 
- `screen-breakageForm`, or
- `screen-toggleReport`
- if the iframe previews load as they do in the video, then all is good :)
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/Youbs18YwblmJpLrzsDC/395525a1-ddee-4001-8c2d-26803c604b91.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Youbs18YwblmJpLrz …
=> reflect params in the debugger

build/app/public/js/base.js, integration-tests/AltBreakageFlows.js, integration-tests/Mocks.js, schema/__generated__/schema.parsers.mjs, schema/__generated__/schema.types.ts, schema/telemetry-span.json, v2/screens/choice-problem.jsx
This change adds a new telemetry event ('toggleSkipped') for when users skip the toggle step on the choice-category screen.
1. Now sends the 'toggleSkipped' event via the existing telemetry handler
2. Adjusted integration tests to check for the new telemetry event.
3. Updated TypeScript interfaces to include the new event.
1. Navigate to the choice-category screen.
2. Click on the 'Skip this step' link.
3. Verify that the telemetry event 'toggleSkipped' is sent.
4. Check the modified integration tests for the new event validation.
---
**Reviewer:**
=> send telemetry when 'skip' is clicked in alternative flow

.github/workflows/tests.yml, CONTRIBUTING.md, build/app/public/js/base.js, integration-tests/DashboardPage.js, integration-tests/android.spec-int.js, integration-tests/browser.spec-int.js, integration-tests/ios.spec-int.js, integration-tests/macos.spec-int.js, integration-tests/utils/common-flows.js, integration-tests/windows.spec-int.js, package.json, shared/js/ui/hooks/useRipple.js, v2/data-provider.js, v2/navigation.jsx
https://app.asana.com/0/0/1207868371624522/f
Use the recommended approach for splitting up tests.
Now, we can use the `{ tag: '@screenshots' }` on any `test` or `describe` block.
**run all screenshot tests only** 
```
npm run test.int -- --grep @screenshots
```
**run all none-screenshot tests only** 
```
npm run test.int -- --grep-invert @screenshots
```
=> use playwright tags to separate screenshots

build/app/public/js/base.js, integration-tests/Nav.js, shared/js/ui/hooks/useRipple.js, v2/components/main-nav.jsx, v2/navigation.jsx, v2/screens/non-trackers-screen.jsx, v2/screens/trackers-screen.jsx
**Reviewer:**
Correctly manage the history stack, so that the physical (hardware) back button on Android works as expected (closes the dashboard when it should)
This bug was found during this PR https://github.com/duckduckgo/Android/pull/4779
The Android E2E tests caught the bug 😺
=> fixes for android

build/app/public/js/base.js, integration-tests/Mocks.js, integration-tests/android.spec-int.js, schema/__generated__/schema.parsers.mjs, schema/__generated__/schema.types.ts, schema/remote-feature-settings.json, shared/js/browser/android-communication.js, shared/js/browser/common.js, shared/js/browser/utils/communication-mocks.mjs, shared/js/ui/platform-features.mjs, shared/js/ui/views/tests/generate-data.mjs, types.ts, v2/components/protection-header.jsx, v2/data-provider.js
**Reviewer:**
- `npm run preview`
- 1: ensure the default is still 'disabled' on Android
- visit a regular state, like http://localhost:3000/html/android.html?state=cnn
- verify that clicking on 'Website not working?' does nothing 
- 2: now use `?state=webBreakageForm-enabled` and try again
- now, the web breakage form should show
**Update:**
=> put webBreakageForm behind flag, enabled by default

build/app/public/js/base.js, integration-tests/AltBreakageFlows.js, integration-tests/DashboardPage.js, integration-tests/android.spec-int.js, integration-tests/ios.spec-int.js, integration-tests/macos.spec-int.js, integration-tests/windows.spec-int.js, package.json, v2/navigation.jsx
https://app.asana.com/0/1201141132935289/1208104043193957/f
**Before:**
- we were transitioning the UI to the next state, just before we called `window.history.pushState`
- this caused a couple of problems on iOS
- First, the 'preview' you see when dragging from the left or right (to go back or forward) would not be the correct screen
- Second, the actual navigation action when invoked in this manner was broken - it didn't take you back to the screen you were expecting.
**After:**
- this PR just changes the order of execution: we FIRST call `window.history.pushState(...)` which allows iOS to take a 'snapshot' of the correct screen and then we alter the UI.
The videos below show it working correctly on iOS + Android, but if you want to verify locally, you can follow this:
- npm run preview …
=> fixed back + forward swiping

.github/workflows/tests.yml
If the screenshots fail on PR - we just upload the integration-tests folder. 
This allows the PR author to grab/compare/commit them.
=> upload screenshots on failure

build/app/public/js/base.js, schema/__generated__/schema.parsers.mjs, schema/__generated__/schema.types.ts, schema/windows-view-model.json, shared/js/browser/windows-communication.js, shared/js/ui/views/tests/generate-data.mjs
Adding this structure to the view model on Windows will enable translations.
> [!NOTE]
> This is a none-breaking change.
```json
{ 
...,
"localeSettings": { "locale": "en" }
}
```
=> windows: support translations

.github/workflows/release-protection.yml
https://app.asana.com/0/1200835453786799/1209020109305112/f
Prevent Releases from being created from the GitHub UI
This workflow will only run when a release is created from the GitHub UI - the release and git tag will be deleted.
=> ci: add release protection

integration-tests/DashboardPage.js, integration-tests/Mocks.js, integration-tests/windows.spec-int.js, shared/js/browser/windows-communication.js
Sends a `Ping` message to indicate JS readiness. (NOTE: this is a workaround for the legacy messaging system)
=> windows: send a ping

integration-tests/Mocks.js, integration-tests/android.spec-int.js, integration-tests/ios.spec-int.js, integration-tests/macos.spec-int.js, integration-tests/windows.spec-int.js, shared/js/browser/android-communication.js, shared/js/browser/common.js, shared/js/browser/ios-communication.js, shared/js/browser/macos-communication.js, shared/js/browser/utils/communication-mocks.mjs, shared/js/browser/windows-communication.js, types.ts, v2/data-provider.js, v2/screens/breakage-form-screen.jsx
Asana: https://app.asana.com/0/0/1209180773957103/f
Adds a new `privacyDashboardReportBrokenSiteShown` comms method to notify native that the breakage form has been shown
1. Open the [preview](https://deploy-preview-302--ddgdash.netlify.app/app-debug/html/iframe?state=webBreakageForm-enabled&platforms=android%2Cios%2Cmacos%2Cwindows)
2. Open the console
3. Click on “Report a problem with this site” (Android / iOS / macOS / Windows)
4. Confirm that the `ReportBrokenSiteShown` message has been fired
=> Fire message when invoking breakage form

.github/workflows/tests.yml, .github/workflows/update-snapshots.yml, .gitignore
https://app.asana.com/0/1200835453786799/1209359170590869
=> Adding the update-snapshot workflow

.github/workflows/tests.yml, .github/workflows/update-snapshots.yml, .gitignore, integration-tests/DashboardPage.js, integration-tests/Extension.js, integration-tests/Mocks.js, integration-tests/Nav.js, integration-tests/android.spec-int.js, integration-tests/browser.spec-int.js, integration-tests/helpers.js, integration-tests/ios.spec-int.js, integration-tests/macos.spec-int.js, integration-tests/utils/common-flows.js, integration-tests/utils/states-with-fixtures.js, integration-tests/windows.spec-int.js, package-lock.json, playwright.config.ts, shared/js/browser/communication.js, shared/js/browser/utils/browser-mocks.mjs, shared/js/browser/utils/communication-mocks.mjs, shared/js/ui/views/tests/generate-data.mjs, shared/js/ui/views/tests/states-with-fixtures.js
https://app.asana.com/0/1200835453786799/1209359170590866
=> fix playwright tests with better mock separation

.npmrc, integration-tests/DashboardPage.js, package.json, tsconfig.json
Node 22.14 introduces stricter ESM/require checking which results in the following error in CI:
```
Error: require() of ES Module .../privacy-dashboard/shared/js/ui/views/tests/generate-data.mjs from .../privacy-dashboard/integration-tests/utils/states-with-fixtures.js not supported.
Instead change the require of .../privacy-dashboard/shared/js/ui/views/tests/generate-data.mjs to a dynamic import() which is available in all CommonJS modules.
```
Trying to fix this at the config level without having to resort to dynamic imports. 
1. Force your node version to 22.14 (do not rely on .nvmrc)
2. Run `npm run test.int` and watch for errors
=> Node 22.14 fix

shared/data/text.js, shared/locales/bg/toggle-report.json, shared/locales/cs/toggle-report.json, shared/locales/da/toggle-report.json, shared/locales/de/toggle-report.json, shared/locales/el/toggle-report.json, shared/locales/en/toggle-report.json, shared/locales/es/toggle-report.json, shared/locales/et/toggle-report.json, shared/locales/fi/toggle-report.json, shared/locales/fr/toggle-report.json, shared/locales/hr/toggle-report.json, shared/locales/hu/toggle-report.json, shared/locales/it/toggle-report.json, shared/locales/lt/toggle-report.json, shared/locales/lv/toggle-report.json, shared/locales/nb/toggle-report.json, shared/locales/nl/toggle-report.json, shared/locales/pl/toggle-report.json, shared/locales/pt/toggle-report.json, shared/locales/ro/toggle-report.json, shared/locales/ru/toggle-report.json, shared/locales/sk/toggle-report.json, shared/locales/sl/toggle-report.json, shared/locales/sv/toggle-report.json, shared/locales/tr/toggle-report.json
Asana task: https://app.asana.com/1/137249556945/task/1210237517707665?focus=true
This is a follow up to https://github.com/duckduckgo/privacy-dashboard/pull/424 
- Added translations for the string "Anonymous experiment groups for feature testing"
- Renamed the locale key `dynamic_atb` to `dynamic_experimentGroups` to better reflect the copy change
Out of scope for this PR: renaming the `atb` id that gets passed from native platforms to the dashboard. 
1. Visit the [Breakage Form preview in French](https://deploy-preview-435--ddgdash.netlify.app/app-debug/html/iframe?locale=es&state=locale-fr&screen=breakageFormFinalStep) 
1b. Alternatively, run the preview locally and pass any locale into the mock data. Example: `{ localeSettings: { locale: 'es' } }`
2. Expand …
=> Experiment groups translations and locale key update
